[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/color",
    "projects/color-macro",
    "projects/color-parser",
    "projects/color-gradient",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
