[workspace]
members = ["projects/*"]
default-members = [
    "projects/color",
    "projects/color-macro",
    "projects/color-parser",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
