[package]
name = "f01"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "A float in range 0-1"
repository = "https://github.com/oovm/tailwind-rs"
documentation = "https://docs.rs/const-css-color"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["*.json"]
